openapi: 3.0.0
info:
  title: My API
  description: API documentation for Lambda functions
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
paths:
  /xyz:
    get:
      summary: Get XYZ data
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  requestId:
                    type: string
    post:
      summary: Create XYZ data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '201':
          description: Created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                  requestId:
                    type: string
