name: Deploy to QA Environment

on:
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'
      - 'lambda_functions/**'
      - 'layers/**'
      - 'scripts/**'
      - '.github/workflows/terraform-deploy.yml'
      - '.github/workflows/deploy-qa.yml'

env:
  AWS_REGION: ap-south-1

jobs:
  validate:
    name: Validate Terraform
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.5.0"
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Make build script executable
      run: chmod +x scripts/build.sh
      
    - name: Validate Terraform configuration
      run: ./scripts/build.sh validate

  plan:
    name: Plan Terraform Changes
    runs-on: ubuntu-latest
    needs: validate
    outputs:
      plan-file: ${{ steps.plan.outputs.plan-file }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.5.0"
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Make build script executable
      run: chmod +x scripts/build.sh
      
    - name: Plan Terraform changes
      id: plan
      run: |
        ./scripts/build.sh plan qa
        echo "plan-file=terraform-plan-qa.tfplan" >> $GITHUB_OUTPUT
      
    - name: Upload plan file
      uses: actions/upload-artifact@v4
      with:
        name: terraform-plan-qa
        path: terraform-plan-qa.tfplan
        retention-days: 1

  wait-for-approval:
    name: Wait for QA Deployment Approval
    runs-on: ubuntu-latest
    needs: [validate, plan]
    outputs:
      approved: ${{ steps.approval.outputs.approved }}
    steps:
    - name: Wait for approval
      id: approval
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ secrets.GITHUB_TOKEN }}
        approvers: mohammadn0man
        minimum-approvals: 1
        exclude-workflow-initiator-as-approver: false

  deploy:
    name: Deploy to QA
    uses: ./.github/workflows/terraform-deploy.yml
    needs: [validate, plan, wait-for-approval]
    if: needs.wait-for-approval.outputs.approved == 'true'
    with:
      environment: qa
      aws-region: ${{ vars.AWS_REGION }}
      plan-file: ${{ needs.plan.outputs.plan-file }}
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 