name: Deploy to Dev Environment

on:
  workflow_dispatch:
    inputs:
      skip_approval:
        description: 'Skip approval step (for testing only)'
        required: false
        default: false
        type: boolean
      force_deploy:
        description: 'Force deployment even if no changes detected'
        required: false
        default: false
        type: boolean
  push:
    branches: [ develop ]
    paths:
      - 'terraform/**'
      - 'lambda_functions/**'
      - 'layers/**'
      - 'scripts/**'
      - '.github/workflows/terraform-plan.yml'
      - '.github/workflows/terraform-validate.yml'
      - '.github/workflows/terraform-deploy.yml'
      - '.github/workflows/deploy-dev.yml'

permissions:
  contents: read
  pull-requests: write
  issues: write

env:
  AWS_REGION: ${{ vars.AWS_REGION }}

jobs:
  validate:
    uses: ./.github/workflows/terraform-validate.yml
    with:
      environment: dev
      aws-region: ${{ vars.AWS_REGION }}
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      razorpay-key-id: ${{ secrets.RAZORPAY_KEY_ID }}
      razorpay-key-secret: ${{ secrets.RAZORPAY_KEY_SECRET }}
      razorpay-webhook-secret: ${{ secrets.RAZORPAY_WEBHOOK_SECRET }}

  plan:
    uses: ./.github/workflows/terraform-plan.yml
    needs: validate
    with:
      environment: dev
      aws-region: ${{ vars.AWS_REGION }}
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      razorpay-key-id: ${{ secrets.RAZORPAY_KEY_ID }}
      razorpay-key-secret: ${{ secrets.RAZORPAY_KEY_SECRET }}
      razorpay-webhook-secret: ${{ secrets.RAZORPAY_WEBHOOK_SECRET }}
      
  deploy:
    name: Deploy to Dev
    uses: ./.github/workflows/terraform-deploy.yml
    needs: [validate, plan]
    with:
      environment: dev
      aws-region: ${{ vars.AWS_REGION }}
      plan-file: ${{ needs.plan.outputs.plan-file }}
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
