name: Terraform Validate

on:
  workflow_call:
    inputs:
      aws-region:
        required: false
        type: string
        default: ${{ vars.AWS_REGION }}
        description: 'AWS region for validation'
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true

jobs:
  validate:
    name: Validate Terraform
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.5.0"
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.aws-access-key-id }}
        aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
        
    - name: Make build script executable
      run: chmod +x scripts/build.sh
      
    - name: Validate Terraform configuration
      run: ./scripts/build.sh validate 